[package]
name = "wow"
version = "0.1.0"
edition = "2024"


[dependencies]
gtk4 = "0.9.6"
gdk4 = "0.9.6"
gtk4-layer-shell = "0.5.0"
gio = "0.20.11"
glib = "0.20.10"
hypr-ipc = { path = "../hypr-ipc" }
