[package]
name = "wow"
version = "0.1.0"
edition = "2024"


[dependencies]
gtk4 = "0.9.6"
gtk4-layer-shell = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.33"
tokio = { version = "1.45.0", features = ["full"] }
